version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    command: python main.py

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
      - ./tests:/tests
    command: python -m unittest discover -v
